[Variables]
; Change Device0 and Device1 to the names of the two sound devices you want to
; toggle between.
; The names must match how the name appears in Windows list of sound devices.
; To change the sound device names in Windows, right-click the speaker icon in
; the bottom right and open Sound -> Playback -> Properties on your device.
; Use only letters from the English alphabet in the names.
Device0Name=Speakers
Device1Name=Speakers on headset

; Choose between Dark or Light theme
Theme=Light

; Change these to scale the image
ImageWidth=50
ImageHeight=50

; Don't change these if you don't know what you are doing.
CurrentDeviceNumber=0
ShowSettings=0
